### PR TITLE
New feature - optional args

### PR DESCRIPTION
**Pull request by sp00ne**
This is in response to the issue I submitted :) I hope this pull request is up to your standards and liking!

Tell me what you think :)

### CODE REVIEW

**Comment by sarahdayan** [comment]
Hey sp00ne, and thanks for the heads up! I was just recently refactoring the plugin to make the code cleaner. Your suggestion is great and instead of merging your pull request I'll use the occasion to include it in the refact directly.

**Comment by sarahdayan** [comment]
Hey! Version 1.2.0 solves this issue. Thanks for your suggestion :)

**Comment by sp00ne** [comment]
Choosing to cut and paste the code into the refactor is poor practice imo. But nonetheless, you are welcome.

**Comment by sarahdayan** [comment]
Hey man, sorry I didn't know better. I'll do for next time.

**Pull request closed without merging**
